### ISSUE TITLE
Compatibility module for Bukkit Material, Sound, etc.

### ISSUE THREAD

**Issue by lgou2w** [lgou2w/ldk#15]
Use [XMaterial](https://github.com/25/EnchantmentsEnhance/blob/ca17504f2f1cb78dcd50f7a82b0e5c2f790f0119/EnchantmentsEnhance-Core/src/main/java/org/pixeltime/enchantmentsenhance/util/XMaterial.java) in [25/EnchantmentsEnhance](https://github.com/25/EnchantmentsEnhance) to compare item type, and achieve good compatibility with 1.13 higher version server. Can I package `XMaterial` and `Sound` separately in the `ldk-bukkit-compatibility` module and open source with the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0.txt) license? @25

**Comment by 25** [comment]
I have only helped the XMaterial, so I redirected to this question [Leonard Ong Rui Fu](https://bitbucket.org/Hex_27/) since he is the author.

**Comment by lgou2w** [comment]
okay, thanks

**Comment by 25** [comment]
@MrBlobman Requesting license for sounds compatibility library.

**Comment by MrBlobman** [comment]
I assume you are referring to https://gist.github.com/MrBlobman/64db96857209d93598300ace9d2b02d0? If so I've added the MIT header to it, if you need anything more please just ask :) I am not as active on this account but I do get the emails if you decided to depend on any libraries and try to maintain things as needed even if adding features has slowed down.

**Comment by 25** [comment]
@MrBlobman That is perfect. Thank you!😄

**Comment by lgou2w** [comment]
@MrBlobman Thanks, I will. If there is any activity, please review this issue.

**Comment by 25** [comment]
Received the license from XMaterial's author. I am starting the integration process with bukkit materials.

**Comment by lgou2w** [comment]
For all changes, please see #17, #19
