### ISSUE TITLE
Offline Player Item Delivery.

### ISSUE THREAD

**Issue by 25** [lgou2w/ldk#16]
Requesting tools for sending itemstack/economy to an offline player.

**Comment by lgou2w** [comment]
I think I can rely on the `ldk` library to make this functionality. Instead of adding productivity features to ldk.

**Comment by lgou2w** [comment]
I am trying to make this feature using ldk, I will inform you of any progress.

**Comment by lgou2w** [comment]
But this is just a demo. It should not be added to ldk

**Comment by 25** [comment]
I appreciate the demo.
