### ISSUE TITLE
Naming consistency

### ISSUE THREAD

**Issue by 25** [lgou2w/ldk#61]
Rename `XMaterial` to `Materials` to keep consistency.

**Comment by lgou2w** [comment]
XMaterial has existed since [`0.0.1-beta2`](https://github.com/lgou2w/ldk/commit/1accd5), and if you do, many project dependencies will be destroyed.

**Comment by lgou2w** [comment]
But for kotlin, you can do this with `typealias Materials = XMaterial`. For java, you can't enjoy it.
